apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: occupancies.example.digi.dev
spec:
  group: example.digi.dev
  names:
    kind: Occupancy
    listKind: OccupancyList
    plural: occupancies
    singular: occupancy
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              egress:
                properties:
                  detected:
                    properties:
                      de_id:
                        type: boolean
                      desc:
                        type: string
                      driver_managed:
                        type: boolean
                      eoio:
                        type: boolean
                      flow:
                        type: string
                      link:
                        type: boolean
                      offload:
                        type: boolean
                      pause:
                        type: boolean
                    type: object
                type: object
              mount:
                properties:
                  mock.digi.dev/v1/occupancies:
                    additionalProperties:
                      properties:
                        generation:
                          type: number
                        mode:
                          type: string
                        spec:
                          properties:
                            meta:
                              properties:
                                gen_interval:
                                  type: number
                                managed:
                                  type: boolean
                                seed:
                                  type: number
                              type: object
                            obs:
                              properties:
                                battery_level:
                                  type: number
                                dbm:
                                  type: string
                                motion_detected:
                                  type: boolean
                                supply_voltage:
                                  type: string
                              type: object
                          type: object
                        status:
                          type: string
                      type: object
                    type: object
                type: object
              obs:
                properties:
                  dbm:
                    type: string
                  motion_detected:
                    type: boolean
                  supply_voltage:
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
